// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel Circles
#pragma kernel Clear
#pragma kernel Bresenham

struct CircleData
{
    float2 origin;
    float2 velocity;
    float radius;
};

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
shared RWTexture2D<float4> Result;
StructuredBuffer<CircleData> _circlesBuffer;

int _texResolution;
float _time;
int2 _startPoint;
int2 _endPoint;
float4 _clearColor;
float4 _circleColor;

float Random(float value, float seed = 0.37)
{
    float random = frac(sin(value + seed) * 124238.95314);
    return random;
}

float2 Random2(float value)
{
    return float2(
        Random(value, 7.458),
        Random(value, 2.956)
        );
}

void PlotOne(int x, int y, int2 centre)
{
    Result[uint2(centre.x + x, centre.y + y)] = _circleColor;
}

void plotEight(int x, int y, int2 centre)
{
    PlotOne(x, y, centre); PlotOne(y, x, centre);
    PlotOne(x, -y, centre); PlotOne(y, -x, centre);
    PlotOne(-x, y, centre); PlotOne(-y, x, centre);
    PlotOne(-x, -y, centre); PlotOne(-y, -x, centre);
}

void DrawCircle( int2 centre, int radius ) {
    int x = 0;
    int y = radius;
    int d = 1 - radius;

    while (x < y){
        if (d < 0){
            d += 2 * x + 3;
        }else{
            d += 2 * (x - y) + 5;
            y--;
        }
		
        plotEight(x, y, centre);

        x++;
    }
}

[numthreads(8,8,1)]
void Clear(uint3 id : SV_DispatchThreadID)
{
    // TODO: insert actual code here!
    Result[id.xy] = _clearColor;
}

[numthreads(16,1,1)]
void Circles(uint3 id : SV_DispatchThreadID)
{
    // TODO: insert actual code here!
    int2 centre = (int2)(_circlesBuffer[id.x].origin + _circlesBuffer[id.x].velocity * _time);
    int radius = (int)_circlesBuffer[id.x].radius;
    
    while (centre.x < 0)
    {
        centre.x += _texResolution;
    }
    while (centre.y < 0)
    {
        centre.y += _texResolution;
    }
    while (centre.x > _texResolution)
    {
        centre.x -= _texResolution;
    }
    while (centre.y > _texResolution)
    {
        centre.y -= _texResolution;
    }
    
    DrawCircle(centre, radius);
}

[numthreads(1,1,1)]
void Bresenham(uint3 id : SV_DispatchThreadID)
{
    int x0 = _startPoint.x;
    int y0 = _startPoint.y;
    int x1 = _endPoint.x;
    int y1 = _endPoint.y;

    int dx = abs(x1 - x0);
    int dy = abs(y1 - y0);

    // Direction: which way are we stepping?
    int sx = (x0 < x1) ? 1 : -1;
    int sy = (y0 < y1) ? 1 : -1;

    int error = dx - dy;   // starting error score

    while (true)
    {
        // Paint this pixel WHITE
        Result[int2(x0, y0)] = _circleColor;

        // Reached the end? Stop!
        if (x0 == x1 && y0 == y1) break;

        int e2 = 2 * error;

        // Adjust x
        if (e2 > -dy) {
            error -= dy;
            x0 += sx;
        }

        // Adjust y
        if (e2 < dx) {
            error += dx;
            y0 += sy;
        }
    }
}
