// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

struct Vertex
{
    float3 position;
    float3 normal;
};

StructuredBuffer<Vertex> initial_buffer;
RWStructuredBuffer<Vertex> vertex_buffer;

float _radius;
float _delta;

[numthreads(1,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float3 initialPosition = initial_buffer[id.x].position;
    float3 deformPosition = float3(normalize(initialPosition) * _radius * 0.01);
    float3 lerpedPosition = lerp(initialPosition, deformPosition, _delta);
    
    float3 initialNormals = initial_buffer[id.x].normal;
    float3 deformNormals = normalize(initialPosition);
    float3 lerpedNormals = lerp(initialNormals, deformNormals, _delta);
    
    vertex_buffer[id.x].position = lerpedPosition;
    vertex_buffer[id.x].normal = lerpedNormals;
}
