// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel HorzPass
#pragma kernel Highlight

Texture2D<float4> source;
RWTexture2D<float4> horzOutput;
RWTexture2D<float4> output;
float radius;
float edgeWidth;
float shade;
float4 center;
int blurRadius;
uint width, height;

float inCircle( float2 pt, float2 center, float radius, float edgeWidth ){
    float len = length(pt - center);
    return 1.0 - smoothstep(radius-edgeWidth, radius, len);
}

void GetTextureDimensions(Texture2D<float4> tex)
{
    tex.GetDimensions(width, height);
}

[numthreads(8, 8, 1)]
void HorzPass(uint3 id : SV_DispatchThreadID)
{
    GetTextureDimensions(source);
    
    float4 color = 0;
    int left = max(0, (int)id.x - blurRadius);
    int count = min(blurRadius, (int)id.x) + min(blurRadius, width - (int)id.x);
    
    uint2 index = uint2((uint)left, id.y);
    
    [unroll(100)]
    for (int x = 0; x < count; x++)
    {
        color += source[index];
        index.x++;
    }
    
    color /= (float)count;
    horzOutput[id.xy] = color;
}

float4 CombinePass(uint3 id)
{
    float4 color = 0;
    int top = max(0, (int)id.y - blurRadius);
    int count = min(blurRadius, (int)id.y) + min(blurRadius, height - (int)id.y);
    
    uint2 index = uint2(id.x, (uint)top);
    
    [unroll(100)]
    for (int y = 0; y < count; y++)
    {
        color += horzOutput[index];
        index.y++;
    }
    
    color /= (float)count;
    
    float highlight = inCircle((float2)id.xy, center.xy, radius, edgeWidth);
    
    float4 sourceColor = source[id.xy];
    float4 shadedBlurColor = color * shade;
    
    color = lerp(shadedBlurColor, sourceColor, highlight);
    
    return color;
}

[numthreads(8, 8, 1)]
void Highlight(uint3 id : SV_DispatchThreadID)
{
    output[id.xy] = CombinePass(id);
}