// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

Texture2D<float4> source;
RWTexture2D<float4> output;
float radius;
float edgeWidth;
int lines;
float4 tintColor;
float tintStrength;
float time;
int resolutionDivisor;

float random (float2 pt, float seed) {
    const float a = 12.9898;
    const float b = 78.233;
    const float c = 43758.543123;
    return frac(sin(dot(pt, float2(a, b)) + seed) * c );
}

float inCircle( float2 pt, float2 center, float radius, float edgeWidth ){
    float len = length(pt - center);
    return 1.0 - smoothstep(radius-edgeWidth, radius, len);
}

[numthreads(8, 8, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    uint2 index = (uint2(id.x, id.y) / resolutionDivisor) * resolutionDivisor;
    float noise = random((float2)id.xy, time);
    float3 srcColor = lerp(source[id.xy].rgb * 2, source[index].rgb, noise);
    
    float3 grayScale = (srcColor.r + srcColor.g + srcColor.b) / resolutionDivisor;
    float3 tinted = grayScale * tintColor;
    float3 finalColor = lerp(srcColor, tinted, tintStrength);
    
    uint2 sourceDimensions;
    source.GetDimensions(sourceDimensions.x, sourceDimensions.y);
    
    float uvY = (float)id.y / sourceDimensions.y;
    float scanLine = saturate(smoothstep(0.1, 0.2, frac(uvY * lines + time * resolutionDivisor)) + resolutionDivisor / 10);
    finalColor = lerp(source[id.xy].rgb * 0.5, finalColor, scanLine);
    
    float black = 0;
    float2 pt = (float2)id.xy;
    float2 centre = (float2)sourceDimensions * 0.5;
    
    centre.x -= radius * 0.7;
    //centre.y += resolutionDivisor / 10.0;
    float leftLens = inCircle(pt, centre, radius, edgeWidth);
    
    centre.x += radius * 1.4;
    float rightLens = inCircle(pt, centre, radius, edgeWidth);
    
    float inVision = saturate(leftLens + rightLens);
    finalColor = lerp(black, finalColor, inVision);
    
    output[id.xy] = float4(finalColor, 1);
}